name: Pull Request Labeler
on:
  pull_request:
    types: [opened, reopened]
    branches-ignore:
      - production

jobs:
  add_label:
    permissions:
      contents: read 
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4 
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/workflows/templates/labeler-config.yml
