apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "app-backend.fullname" . }}
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "app-backend.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "app-backend.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
