kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "app-backend.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app-backend.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "patch"]

